#!/usr/bin/env ruby

require "pathname"

def create_zip(files)
  system "trash", "tmp" if Pathname("tmp").exist?
  Pathname("tmp").mkpath
  files.each do |name, content|
    Pathname("tmp/#{name}").write(content)
  end
  Dir.chdir("tmp") do
    system "7za", "a", "output.7z", *files.keys
  end
  Pathname("tmp/output.7z").open("rb", &:read)
end

def generate_archive(real, fake)
  expanded = real.size

  16.times do |j|
    extname = j == 0 ? "jpg" : "7z"
    real_files = (0..15).map{|i| "%x.#{extname}" % i}.zip(([real] + [fake] * 15).shuffle).to_h
    fake_files = (0..15).map{|i| "%x.#{extname}" % i}.zip([fake] * 16).to_h
    real = create_zip(real_files)
    fake = create_zip(fake_files)
    max_size = [real.size, fake.size].max
    real += "\x00" * (max_size - real.size)
    fake += "\x00" * (max_size - fake.size)
    expanded *= 16
  end

  open("archive.7z", "wb") do |fh|
    fh.write real
  end

  puts "Expanded size: #{expanded}"
  puts "Compressed size: #{real.size}"
  puts "Ratio: #{expanded / real.size}"
end

message = open("yes.jpg", "rb").read
fake_message = open("no.jpg", "rb").read
generate_archive(message, fake_message)
